version: "3.9"

services:
  my-java-app:
    build:
     context: .
    volumes:
      - ./:/app
    command: mvn exec:java -X
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myusername
      SPRING_DATASOURCE_PASSWORD: mypassword

  my-java-app-test:
    build:
     context: .
    volumes:
      - ./:/app
    command: mvn test

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: